In [1]:
from sklearn.datasets import make_classification
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn. preprocessing import OneHotEncoder

#Задание 1 
Какова вероятность отправиться на прогулку если идёт дождь, при наличии следующих наблюдений?

In [4]:
data = [
        ('солнечно', True),
        ('снег', False),
        ('облачно', False),
        ('дождь', False),
        ('солнечно', True),
        ('снег', False),
        ('облачно', True),
        ('снег', False),
        ('солнечно', False),
        ('облачно', True),
        ('снег', True),
        ('солнечно', True),
        ('дождь', False),
        ('дождь', True),
        ('облачно', True),
]

In [5]:
df = pd.DataFrame(data, columns = ["wheather","go"])
df

wheather     go
0   солнечно   True
1       снег  False
2    облачно  False
3      дождь  False
4   солнечно   True
5       снег  False
6    облачно   True
7       снег  False
8   солнечно  False
9    облачно   True
10      снег   True
11  солнечно   True
12     дождь  False
13     дождь   True
14   облачно   True

In [6]:
rain = len(df.loc[df['wheather']=='дождь'])/len(df)
go = len(df.loc[df['go']==True])/len(df)
p_rain_and_go = len(df.loc[(df['wheather'] == 'дождь')&(df['go'] == True)])/len(df.loc[df['go']==True])
p_go_if_rain = (go*p_rain_and_go)/rain
print(p_go_if_rain)

0.3333333333333333


In [8]:
rain

0.2

In [10]:
encoder = OneHotEncoder(handle_unknown='ignore')
encoder_df = pd.DataFrame(encoder. fit_transform(df[['wheather']]). toarray ())
final_df = df.join (encoder_df)
final_df.drop('wheather', axis= 1 , inplace= True )
final_df.columns = ['go', 'rain', 'cloudy', 'snow', 'sun']
print(final_df)

       go  rain  cloudy  snow  sun
0    True   0.0     0.0   0.0  1.0
1   False   0.0     0.0   1.0  0.0
2   False   0.0     1.0   0.0  0.0
3   False   1.0     0.0   0.0  0.0
4    True   0.0     0.0   0.0  1.0
5   False   0.0     0.0   1.0  0.0
6    True   0.0     1.0   0.0  0.0
7   False   0.0     0.0   1.0  0.0
8   False   0.0     0.0   0.0  1.0
9    True   0.0     1.0   0.0  0.0
10   True   0.0     0.0   1.0  0.0
11   True   0.0     0.0   0.0  1.0
12  False   1.0     0.0   0.0  0.0
13   True   1.0     0.0   0.0  0.0
14   True   0.0     1.0   0.0  0.0


In [11]:
X = final_df.drop(["go"], axis = 1)
Y = final_df["go"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.1)

In [13]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((13, 4), (13,), (2, 4), (2,))

In [14]:
knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [15]:
knn.predict([[1, 0, 0, 0]])

C:\Users\Aron\Desktop\Учеба\4 семестр\Машинное обучение\Jupiter nouts\venv\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([False])

Задание 2

*загрузите датасет для классификации, проведите предобработку, выделите целевой признак и предикторы, разбейте данные на обучающую и тестовую выборку;

*Масштабируйте числовые признаки

*В случае дисбаланса проведите балансировку

*решите задачу классификации на ваших данных с использованием рассмотренных моделей sklearn: knn, NB, Logistic Regression, SVM.

*Не забудьте подобрать гиперпараметры.

*вычислите значения метрик Accuracy, Precision, Recall, F1, ROC AUC score

In [2]:
Cards = pd.read_csv("../data/card_transdata.csv")
Cards

distance_from_home  distance_from_last_transaction  \
0                57.877857                        0.311140   
1                10.829943                        0.175592   
2                 5.091079                        0.805153   
3                 2.247564                        5.600044   
4                44.190936                        0.566486   
...                    ...                             ...   
999995            2.207101                        0.112651   
999996           19.872726                        2.683904   
999997            2.914857                        1.472687   
999998            4.258729                        0.242023   
999999           58.108125                        0.318110   

        ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                             1.945940              1.0        1.0   
1                             1.294219              1.0        0.0   
2                             0.427715              1.0        0.0   
3                             0.362663              1.0        1.0   
4                             2.222767              1.0        1.0   
...                                ...              ...        ...   
999995                        1.626798              1.0        1.0   
999996                        2.778303              1.0        1.0   
999997                        0.218075              1.0        1.0   
999998                        0.475822              1.0        0.0   
999999                        0.386920              1.0        1.0   

        used_pin_number  online_order  fraud  
0                   0.0           0.0    0.0  
1                   0.0           0.0    0.0  
2                   0.0           1.0    0.0  
3                   0.0           1.0    0.0  
4                   0.0           1.0    0.0  
...                 ...           ...    ...  
999995              0.0           0.0    0.0  
999996              0.0           0.0    0.0  
999997              0.0           1.0    0.0  
999998              0.0           1.0    0.0  
999999              0.0           1.0    0.0  

[1000000 rows x 8 columns]

In [17]:
Cards.isnull().sum()

distance_from_home                0
distance_from_last_transaction    0
ratio_to_median_purchase_price    0
repeat_retailer                   0
used_chip                         0
used_pin_number                   0
online_order                      0
fraud                             0
dtype: int64

In [3]:
Cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column                          Non-Null Count    Dtype  
---  ------                          --------------    -----  
 0   distance_from_home              1000000 non-null  float64
 1   distance_from_last_transaction  1000000 non-null  float64
 2   ratio_to_median_purchase_price  1000000 non-null  float64
 3   repeat_retailer                 1000000 non-null  float64
 4   used_chip                       1000000 non-null  float64
 5   used_pin_number                 1000000 non-null  float64
 6   online_order                    1000000 non-null  float64
 7   fraud                           1000000 non-null  float64
dtypes: float64(8)
memory usage: 61.0 MB


In [4]:
x = Cards.drop(["fraud"], axis = 1)
y = Cards["fraud"]

In [5]:
from imblearn.under_sampling import RandomUnderSampler

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [7]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((850000, 7), (850000,), (150000, 7), (150000,))

In [8]:
undersample = RandomUnderSampler()
x_under, y_under = undersample.fit_resample(X_train, y_train)

In [9]:
x_under.shape, y_under.shape, X_test.shape, y_test.shape

((148488, 7), (148488,), (150000, 7), (150000,))

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(x_under)
X_train_scaled = scaler.transform(x_under)
X_test_scaled  = scaler.transform(X_test)

KNN

In [11]:
knn = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p=2)
knn.fit(X_train_scaled, y_under)
y_knn_pred = knn.predict(X_test_scaled)

knn - это объект классификатора K ближайших соседей в библиотеке Scikit-learn.

n_neighbors - число ближайших соседей, которые будут использоваться для классификации нового наблюдения.

metric - метрика расстояния, которая используется для определения расстояния между двумя наблюдениями. В данном случае, используется метрика Минковского.

p - параметр, который определяет степень метрики Минковского. Если p=1, то используется манхэттенское расстояние, а если p=2, то евклидово расстояние.


In [12]:
print(classification_report(y_test, y_knn_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00    136841
         1.0       0.94      1.00      0.97     13159

    accuracy                           0.99    150000
   macro avg       0.97      1.00      0.98    150000
weighted avg       0.99      0.99      0.99    150000



classification_report - это функция из библиотеки Scikit-learn, которая позволяет вывести отчет о точности классификации. Она выводит статистику о результате работы модели, включая метрики точности, полноты и f1-меры для каждого класса. 

Метрики, которые включены в classification_report:
точность (precision): доля правильно угаданных положительных классов относительно всех положительных классов
полнота (recall): доля правильно угаданных положительных классов относительно всех истинных положительных классов
f1-мера (f1-score): среднее гармоническое точности и полноты
поддержка (support): количество объектов в классе в тестовой выборке

Из classification_report можно понять, какая точность у модели для каждого класса, насколько полна модель для каждого класса, а также средние значения точности, полноты и f1-меры для всех классов. Отчет также позволяет определить, какие классы были легко или трудно классифицировать, основываясь на их точности и полноте.

Например, если точность и полнота очень высоки для определенного класса, то можно сделать вывод, что модель хорошо различает этот класс от остальных. Если же значения метрик для какого-то класса низкие, то это может указывать на проблемы в модели и/или данные, или же на то, что данный класс сложно различить от других.

In [13]:
accuracy_score(y_test, y_knn_pred)

0.9944266666666667

In [18]:
y_knn_pred1 = knn.predict(X_test)
print(classification_report(y_test, y_knn_pred1))

C:\Users\Aron\Desktop\Учеба\4 семестр\Машинное обучение\Jupiter nouts\venv\lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


              precision    recall  f1-score   support

         0.0       1.00      0.00      0.00    136841
         1.0       0.09      1.00      0.16     13159

    accuracy                           0.09    150000
   macro avg       0.54      0.50      0.08    150000
weighted avg       0.92      0.09      0.02    150000



In [14]:
confusion_matrix(y_test, y_knn_pred)

array([[136013,    828],
       [     8,  13151]], dtype=int64)

In [16]:
import joblib
joblib.dump(knn, 'model_classifier.h5')
loaded_model = joblib.load("model_classifier.h5")
loaded_model

KNeighborsClassifier(n_neighbors=7)

In [30]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_knn_pred, multi_class='ovo')

0.9966387628729996

LOGISTIC REGRESSION

In [31]:
from sklearn.linear_model import LogisticRegression


clf = LogisticRegression(random_state=0).fit(X_train_scaled, y_under)
y_lr_pred = clf.predict(X_test_scaled)
print(classification_report(y_test, y_lr_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96    136799
         1.0       0.58      0.95      0.72     13201

    accuracy                           0.94    150000
   macro avg       0.79      0.94      0.84    150000
weighted avg       0.96      0.94      0.94    150000



In [32]:
accuracy_score(y_test, y_lr_pred)

0.9353

In [33]:
confusion_matrix(y_test, y_lr_pred)

array([[127715,   9084],
       [   621,  12580]], dtype=int64)

In [34]:
roc_auc_score(y_test, y_lr_pred, multi_class='ovo')

0.9432770575264525

NB

In [35]:
gnb = GaussianNB()
gnb.fit(X_train_scaled, y_under)
y_nb_pred = gnb.predict(X_test_scaled)
print(classification_report(y_test, y_nb_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.93      0.96    136799
         1.0       0.56      0.97      0.71     13201

    accuracy                           0.93    150000
   macro avg       0.78      0.95      0.83    150000
weighted avg       0.96      0.93      0.94    150000



In [36]:
accuracy_score(y_test, y_nb_pred)

0.9302333333333334

In [37]:
confusion_matrix(y_test, y_nb_pred)

array([[126787,  10012],
       [   453,  12748]], dtype=int64)

In [38]:
roc_auc_score(y_test, y_nb_pred, multi_class='ovo')

0.9462483741733124

SVM

In [39]:
clf = svm.SVC()
clf.fit(X_train_scaled, y_under)

y_svm_pred = clf.predict(X_test_scaled)
print(classification_report(y_test, y_svm_pred))

              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99    136799
         1.0       0.85      1.00      0.92     13201

    accuracy                           0.98    150000
   macro avg       0.92      0.99      0.95    150000
weighted avg       0.99      0.98      0.98    150000



In [40]:
accuracy_score(y_test, y_svm_pred)

0.9839933333333334

In [41]:
confusion_matrix(y_test, y_svm_pred)

array([[134414,   2385],
       [    16,  13185]], dtype=int64)

In [42]:
roc_auc_score(y_test, y_svm_pred, multi_class='ovo')

0.9906768163189902

Задание 3

Самостоятельно реализуйте метрики Accuracy, Precision, Recall, F1

Самостоятельно реализуйте kNN и Naive Bayes

Метрики: Accuracy

In [50]:
metric = confusion_matrix(y_test, y_nb_pred)
Acc = (metric[0][0] + metric[1][1])/(metric[0][0] + metric[1][1]+metric[0][1]+metric[1][0])
Prec = (metric[0][0])/(metric[0][0]+metric[0][1])
Reca = metric[0][0]/(metric[0][0]+metric[1][1])
F1 = 2/((1/Prec)+(1/Reca))
print('Accuracy =', Acc)
print('Precision =', Prec)
print('Recall =', Reca)
print('F1 =', F1)

Accuracy = 0.9302333333333334
Precision = 0.926812330499492
Recall = 0.9086394094671588
F1 = 0.9176359043765877


In [378]:
from collections import Counter

def euclidean_distance(x1, x2):
    distance = np.sqrt(np.sum((x1-x2)**2))
    return distance

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return predictions

    def _predict(self, x):
        # compute the distance
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]
    
        # get the closest k
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # majority voye
        most_common = Counter(k_nearest_labels).most_common()
        return most_common[0][0]

In [380]:
clf = KNN(k=5)
clf.fit(X_train_scaled, y_under)
predictions = clf.predict(X_test_scaled)

acc = np.sum(predictions == y_test) / len(y_test)
print(acc)

KeyboardInterrupt: 

In [2]:
import numpy as np

class NaiveBayes:

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self._classes = np.unique(y)
        n_classes = len(self._classes)

        # calculate mean, var, and prior for each class
        self._mean = np.zeros((n_classes, n_features), dtype=np.float64)
        self._var = np.zeros((n_classes, n_features), dtype=np.float64)
        self._priors = np.zeros(n_classes, dtype=np.float64)

        for idx, c in enumerate(self._classes):
            X_c = X[y == c]
            self._mean[idx, :] = X_c.mean(axis=0)
            self._var[idx, :] = X_c.var(axis=0)
            self._priors[idx] = X_c.shape[0] / float(n_samples)
            

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        posteriors = []

        # calculate posterior probability for each class
        for idx, c in enumerate(self._classes):
            prior = np.log(self._priors[idx])
            posterior = np.sum(np.log(self._pdf(idx, x)))
            posterior = posterior + prior
            posteriors.append(posterior)

        # return class with the highest posterior
        return self._classes[np.argmax(posteriors)]

    def _pdf(self, class_idx, x):
        mean = self._mean[class_idx]
        var = self._var[class_idx]
        numerator = np.exp(-((x - mean) ** 2) / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator


    def accuracy(y_true, y_pred):
        accuracy = np.sum(y_true == y_pred) / len(y_true)
        return accuracy

In [1]:
    X, y = datasets.make_classification(
        n_samples=1000, n_features=10, n_classes=2, random_state=123
    )
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=123
    )

    nb = NaiveBayes()
    nb.fit(X_train, y_train)
    predictions = nb.predict(X_test)

    print("Naive Bayes classification accuracy", accuracy(y_test, predictions))

NameError: name 'datasets' is not defined